/* ==========================================================================
   Murray Death — Chrome Noir Archive
   Static content data (no backend / no Base44 SDK required)
   ========================================================================== */

const SITE = {
  email: "hello@murraydeath.com",
  instagram: "https://www.instagram.com/murraydeath",
  lightroomHome: "https://lightroom.adobe.com",
};

/* Hero background/frame photo(s), hosted locally in assets/images/hero/.
   One entry today; add more filenames here and the hero will pick a
   different one at random on each page load (see initHeroParallax in
   home.js). */
const HERO_IMAGES = ["https://murraydeathdesigns.github.io/assets/images/hero/aperture.jpg"];

/* Section 02 — The Texture Gallery
   (locally hosted — same source photos as the matching Leak Vault covers) */
const GALLERY_SHOTS = [
  {
    src: "https://murraydeathdesigns.github.io/assets/images/albums/seattle-24.jpg",
    title: "Seattle '24",
    iso: "1600",
    shutter: "1/60",
    lens: "50mm f/1.4",
  },
  {
    src: "https://murraydeathdesigns.github.io/assets/images/albums/edinburgh-24.jpg",
    title: "Edinburgh '24",
    iso: "3200",
    shutter: "1/125",
    lens: "85mm f/1.8",
  },
  {
    src: "https://murraydeathdesigns.github.io/assets/images/albums/chicago-26.jpg",
    title: "Chicago '26",
    iso: "6400",
    shutter: "1/30",
    lens: "35mm f/2.0",
  },
  {
    src: "https://murraydeathdesigns.github.io/assets/images/albums/london-25.jpg",
    title: "London '25",
    iso: "800",
    shutter: "1/200",
    lens: "100mm Macro f/2.8",
  },
];

/* Section 03 — The Leak Vault (Lightroom albums)
   Cover photos are hosted locally in assets/images/albums/ (no more
   media.base44.com hotlinks). The "href" links still point out to each
   real Lightroom shared album, which is intentional. */
const ALBUMS = [
  { name: "Seattle '24", cover: "https://murraydeathdesigns.github.io/assets/images/albums/seattle-24.jpg", href: "https://adobe.ly/4dtrJTU" },
  { name: "San Jose '24", cover: "https://murraydeathdesigns.github.io/assets/images/albums/san-jose-24.jpg", href: "https://adobe.ly/3y6XPV6" },
  { name: "San Diego '24", cover: "https://murraydeathdesigns.github.io/assets/images/albums/san-diego-24.jpg", href: "https://adobe.ly/3UFXP60" },
  { name: "Burbank '24", cover: "https://murraydeathdesigns.github.io/assets/images/albums/burbank-24.jpg", href: "https://adobe.ly/4ewKgOj" },
  { name: "Edinburgh '24", cover: "https://murraydeathdesigns.github.io/assets/images/albums/edinburgh-24.jpg", href: "https://adobe.ly/4eeDAnD" },
  { name: "Vancouver '24", cover: "https://murraydeathdesigns.github.io/assets/images/albums/vancouver-24.jpg", href: "https://adobe.ly/3y5CKua" },
  { name: "Boston '25", cover: "https://murraydeathdesigns.github.io/assets/images/albums/boston-25.jpg", href: "https://adobe.ly/4j7V2xe" },
  { name: "Burbank '25", cover: "https://murraydeathdesigns.github.io/assets/images/albums/burbank-25.jpg", href: "https://adobe.ly/3Qaz6VK" },
  { name: "Van Nuys '25", cover: "https://murraydeathdesigns.github.io/assets/images/albums/van-nuys-25.jpg", href: "https://adobe.ly/4jR6UEC" },
  { name: "Asheville '25", cover: "https://murraydeathdesigns.github.io/assets/images/albums/asheville-25.jpg", href: "https://adobe.ly/47ffOqc" },
  { name: "Carnival '26", cover: "https://murraydeathdesigns.github.io/assets/images/albums/carnival-26.jpg", href: "https://adobe.ly/4fNwB8b" },
  { name: "Cardi '26", cover: "https://murraydeathdesigns.github.io/assets/images/albums/cardi-26.jpg", href: "https://adobe.ly/4rtZoTs" },
  { name: "Its Warm in Tennessee", cover: "https://murraydeathdesigns.github.io/assets/images/albums/its-warm-in-tennessee.jpg", href: "https://adobe.ly/47PRxbk" },
  { name: "St. Louis '26", cover: "https://murraydeathdesigns.github.io/assets/images/albums/st-louis-26.jpg", href: "https://adobe.ly/4wvRvzK" },
  { name: "Chicago '26", cover: "https://murraydeathdesigns.github.io/assets/images/albums/chicago-26.jpg", href: "https://adobe.ly/4wETRwm" },
  { name: "LA '24", cover: "https://murraydeathdesigns.github.io/assets/images/albums/la-24.jpg", href: "https://adobe.ly/4h5w8wA" },
  { name: "Munich '24", cover: "https://murraydeathdesigns.github.io/assets/images/albums/munich-24.jpg", href: "https://adobe.ly/3LoJ8Qt" },
  { name: "Munich Runde 2 '24", cover: "https://murraydeathdesigns.github.io/assets/images/albums/munich-runde-2-24.jpg", href: "https://adobe.ly/3Ugfnci" },
  { name: "NYC '25", cover: "https://murraydeathdesigns.github.io/assets/images/albums/nyc-25.jpg", href: "https://adobe.ly/45yLKXh" },
  { name: "Rexburg '25", cover: "https://murraydeathdesigns.github.io/assets/images/albums/rexburg-25.jpg", href: "https://adobe.ly/4n3JZap" },
  { name: "Seattle '25", cover: "https://murraydeathdesigns.github.io/assets/images/albums/seattle-24.jpg", href: "https://adobe.ly/4lRaT4A" },
  { name: "TSX-donna '26", cover: "https://murraydeathdesigns.github.io/assets/images/albums/tsx-donna-26.jpg", href: "https://adobe.ly/4e3GdKW" },
  { name: "XST62'", cover: "https://murraydeathdesigns.github.io/assets/images/albums/xst62.jpg", href: "https://adobe.ly/430q04l" },
  { name: "Get Halloween Hitched '26", cover: "https://murraydeathdesigns.github.io/assets/images/albums/get-halloween-hitched-26.jpg", href: "https://adobe.ly/3JChMcn" },
  { name: "London '25", cover: "https://murraydeathdesigns.github.io/assets/images/albums/london-25.jpg", href: "https://adobe.ly/4cmjVTu" },
  { name: "The Burg '25", cover: "https://murraydeathdesigns.github.io/assets/images/albums/the-burg-25.jpg", href: "https://adobe.ly/4tdRwGL" },
  { name: "Scotland '25", cover: "https://murraydeathdesigns.github.io/assets/images/albums/scotland-25.jpg", href: "https://lightroom.adobe.com/libraries/29e4b415e3b2440cbd72f93d4cbb24d4/albums/2f07da1699f0410098442c2544c57cb0/assets/47d0ddf2081b410aacb9a0f98fbf1e0b?panel=share&tab=photos" },
];

/* Section 04 — The Chronicle (artwork / sketchbook slideshow)
   Hosted locally in assets/images/chronicle/ — sourced from Murray's own
   "Photos-1-001" export (ink sketches, notebook pages, painted objects),
   no more dependency on a Google Photos share link. */
const CHRONICLE_SLIDES = [
  "https://murraydeathdesigns.github.io/assets/images/chronicle/frame-01.jpg",
  "https://murraydeathdesigns.github.io/assets/images/chronicle/frame-02.jpg",
  "https://murraydeathdesigns.github.io/assets/images/chronicle/frame-03.jpg",
  "https://murraydeathdesigns.github.io/assets/images/chronicle/frame-04.jpg",
  "https://murraydeathdesigns.github.io/assets/images/chronicle/frame-05.jpg",
  "https://murraydeathdesigns.github.io/assets/images/chronicle/frame-06.jpg",
  "https://murraydeathdesigns.github.io/assets/images/chronicle/frame-07.jpg",
  "https://murraydeathdesigns.github.io/assets/images/chronicle/frame-08.jpg",
  "https://murraydeathdesigns.github.io/assets/images/chronicle/frame-09.jpg",
  "https://murraydeathdesigns.github.io/assets/images/chronicle/frame-10.jpg",
  "https://murraydeathdesigns.github.io/assets/images/chronicle/frame-11.jpg",
  "https://murraydeathdesigns.github.io/assets/images/chronicle/frame-12.jpg",
  "https://murraydeathdesigns.github.io/assets/images/chronicle/frame-13.jpg",
  "https://murraydeathdesigns.github.io/assets/images/chronicle/frame-14.jpg",
  "https://murraydeathdesigns.github.io/assets/images/chronicle/frame-15.jpg",
  "https://murraydeathdesigns.github.io/assets/images/chronicle/frame-16.jpg",
  "https://murraydeathdesigns.github.io/assets/images/chronicle/frame-17.jpg",
  "https://murraydeathdesigns.github.io/assets/images/chronicle/frame-18.jpg",
  "https://murraydeathdesigns.github.io/assets/images/chronicle/frame-19.jpg",
  "https://murraydeathdesigns.github.io/assets/images/chronicle/frame-20.jpg",
  "https://murraydeathdesigns.github.io/assets/images/chronicle/frame-21.jpg",
  "https://murraydeathdesigns.github.io/assets/images/chronicle/frame-22.jpg",
  "https://murraydeathdesigns.github.io/assets/images/chronicle/frame-23.jpg",
  "https://murraydeathdesigns.github.io/assets/images/chronicle/frame-24.jpg",
  "https://murraydeathdesigns.github.io/assets/images/chronicle/frame-25.jpg",
  "https://murraydeathdesigns.github.io/assets/images/chronicle/frame-26.jpg",
  "https://murraydeathdesigns.github.io/assets/images/chronicle/frame-27.jpg",
  "https://murraydeathdesigns.github.io/assets/images/chronicle/frame-28.jpg",
  "https://murraydeathdesigns.github.io/assets/images/chronicle/frame-29.jpg",
  "https://murraydeathdesigns.github.io/assets/images/chronicle/frame-30.jpg",
];

/* Bonus page — Camera Collection */
const CAMERAS = [
  {
    name: "Sasquatch 617",
    company: "Sasquatch",
    year: "2026",
    country: "USA",
    film: "120 (Medium Format)",
    lens: "",
    focal: "",
    shutter: "",
    condition: "",
    acquired: "Kickstarter",
    value: "$650",
    notes: "Panoramic camera. 6x17 format on 120 film.",
    history: "",
    photos: [
      "https://murraydeathdesigns.github.io/assets/images/cameras/sasquatch-617-1.jpg",
      "https://murraydeathdesigns.github.io/assets/images/cameras/sasquatch-617-2.jpg",
    ],
  },
  {
    name: "Mamiya C330",
    company: "Mamiya Camera Co.",
    year: "",
    country: "Japan",
    film: "120 (Medium Format)",
    lens: "",
    focal: "80mm",
    shutter: "Leaf",
    condition: "",
    acquired: "",
    value: "",
    notes: "Twin-lens reflex (TLR). Interchangeable lens system on 120 film.",
    history: "",
    photos: ["https://murraydeathdesigns.github.io/assets/images/cameras/mamiya-c330-1.jpg"],
  },
  {
    name: "Pickwik",
    company: "Monarch Mfg. Co.",
    year: "1939",
    country: "U.S.A.",
    film: "127",
    lens: "Graf Achromat F.7.7",
    focal: "50mm",
    shutter: "Leaf (Instantaneous/Time)",
    condition: "Good",
    acquired: "",
    value: "",
    notes: "The Pickwik was a simple, inexpensive camera designed to make photography accessible during the late 1930s. It used 127 film, a popular format for compact cameras of the era.",
    history: "",
    photos: ["https://murraydeathdesigns.github.io/assets/images/cameras/pickwik-1.jpg"],
  },
  {
    name: "Mercury II",
    company: "Universal Camera Corporation",
    year: "1946",
    country: "USA",
    film: "35mm",
    lens: "Universal Tricor f/3.5",
    focal: "35mm",
    shutter: "Rotary Focal Plane",
    condition: "Good",
    acquired: "",
    value: "",
    notes: "Famous for its unique rotary focal plane shutter, which allowed for very high shutter speeds up to 1/1000 or 1/1500 second. The Mercury II was a full-frame 35mm camera, a departure from its half-frame predecessor, the Mercury I.",
    history: "",
    photos: [
      "https://murraydeathdesigns.github.io/assets/images/cameras/mercury-ii-1.jpg",
      "https://murraydeathdesigns.github.io/assets/images/cameras/mercury-ii-2.jpg",
    ],
  },
  {
    name: "No. 3A Autographic Kodak Jr.",
    company: "Eastman Kodak Company",
    year: "1916-1927",
    country: "USA",
    film: "",
    lens: "Kodak Anastigmat F-7.7",
    focal: "170mm",
    shutter: "Kodak Ball Bearing Shutter",
    condition: "Good",
    acquired: "",
    value: "",
    notes: "",
    history: "",
    // Corrected: the photo previously used here actually showed a separate
    // "No.2 Folding Autographic Brownie" (its own entry below). This is a
    // fresh photo of the camera whose badge clearly reads "No.3-A
    // Autographic Kodak Jr."
    photos: ["https://murraydeathdesigns.github.io/assets/images/cameras/no-3a-autographic-kodak-jr-1.jpg"],
  },
  {
    name: "Ensign Carbine No. 1",
    company: "Ensign (Houghtons Ltd.)",
    year: "1930",
    country: "UK",
    film: "120 (Medium Format)",
    lens: "Ensign Meniscus",
    focal: "105mm",
    shutter: "",
    condition: "",
    acquired: "",
    value: "",
    notes: "",
    history: "",
    // No confident match found in the camera photo folder. A box camera
    // labeled "Ful-Vue" (also an Ensign/Houghton model, but a different
    // physical camera than a folding "Carbine") was the closest candidate;
    // rather than mislabel it, it now has its own "Ensign Ful-Vue" entry
    // further down this file. Add a real Carbine No. 1 photo when available.
    photos: [],
  },
  {
    name: "Pacemaker Speed Graphic",
    company: "Graflex",
    year: "1955",
    country: "USA",
    film: "4x5 (Large Format)",
    lens: "Kodak Ektar 152mm f/4.5",
    focal: "152mm",
    shutter: "Kodak Supermatic (X) leaf shutter",
    condition: "Very Good",
    acquired: "",
    value: "",
    notes: "The Speed Graphic was a staple for press photographers for decades, known for its ruggedness and reliability. It features both a focal plane shutter (for high-speed action) and a lens-mounted leaf shutter (for flash synchronization at all speeds).",
    history: "The Pacemaker Speed Graphic, released by Graflex in Rochester, New York, represented the pinnacle of American press photography.",
    photos: ["https://murraydeathdesigns.github.io/assets/images/cameras/pacemaker-speed-graphic-1.jpg", "https://murraydeathdesigns.github.io/assets/images/cameras/pacemaker-speed-graphic-2.jpg"],
  },
  {
    name: "Lubitel 166 Universal",
    company: "LOMO",
    year: "1983",
    country: "Soviet Union",
    film: "120 (Medium Format)",
    lens: "LOMO T-22",
    focal: "75mm",
    shutter: "Leaf shutter",
    condition: "Good",
    acquired: "Ebay",
    value: "",
    notes: "The Lubitel 166 Universal was an affordable and popular entry-level medium format TLR camera from the Soviet Union. The 'Universal' designation means it could shoot both 6x6 and 6x4.5 cm formats on 120 film, and with an adapter, 35mm film.",
    history: "The Lubitel 166 Universal, introduced by the Leningrad Optical Mechanical Association (LOMO).",
    photos: ["https://murraydeathdesigns.github.io/assets/images/cameras/lubitel-166-universal-1.jpg"],
  },
  {
    name: "Daisy Scout 127",
    company: "Daisy Manufacturing Company",
    year: "1939",
    country: "USA",
    film: "",
    lens: "Simple Meniscus",
    focal: "",
    shutter: "Single-speed rotary shutter",
    condition: "",
    acquired: "",
    value: "",
    notes: "Daisy Manufacturing Company is primarily known for its air rifles, making their cameras a less common but interesting part of their history. The camera uses 127 film, a format that was popular for compact cameras but is now largely obsolete, though specialty film can still be found or re-rolled.",
    history: "The Daisy Scout 127, released in 1939 by the Daisy Manufacturing Company.",
    // No confident match found in the supplied camera photo folder for this
    // camera; leaving photos empty (falls back to the camera icon in the UI).
    photos: [],
  },
  {
    name: "Welti",
    company: "Welta",
    year: "1935",
    country: "Germany",
    film: "35mm",
    lens: "",
    focal: "",
    shutter: "",
    condition: "",
    acquired: "",
    value: "",
    notes: "",
    history: "",
    // Medium confidence: the brand name isn't visible in the source photo,
    // but the German folding-camera body plus the Compur/Deckel shutter and
    // Schneider-Xenar lens text visible on it are consistent with a Welti.
    photos: ["https://murraydeathdesigns.github.io/assets/images/cameras/welti-1.jpg"],
  },
  {
    name: "Rolleicord IV",
    company: "Franke & Heidecke",
    year: "1953",
    country: "Germany",
    film: "120 (Medium Format)",
    lens: "",
    focal: "",
    shutter: "",
    condition: "",
    acquired: "",
    value: "",
    notes: "",
    history: "",
    photos: ["https://murraydeathdesigns.github.io/assets/images/cameras/rolleicord-iv-1.jpg"],
  },
  // ---- Added from the camera photo folder: units not in the original
  // archive export, identified visually from nameplates/badges. ----
  {
    name: "No. 2 Folding Autographic Brownie",
    company: "Eastman Kodak Company",
    year: "",
    country: "USA",
    film: "120",
    lens: "",
    focal: "",
    shutter: "Kodak Ball Bearing Shutter",
    condition: "Good",
    acquired: "",
    value: "",
    notes: "A smaller sibling to the No. 3A Autographic Kodak Jr. above; the two are easy to mix up since they share the same Kodak Ball Bearing Shutter badge design, but this one is clearly marked \"No.2 Folding Autographic Brownie\" on its own nameplate.",
    history: "",
    photos: [
      "https://murraydeathdesigns.github.io/assets/images/cameras/no2-folding-autographic-brownie-1.jpg",
      "https://murraydeathdesigns.github.io/assets/images/cameras/no2-folding-autographic-brownie-2.jpg",
    ],
  },
  {
    name: "Ensign Ful-Vue",
    company: "Ensign (Houghton-Butcher)",
    year: "",
    country: "UK",
    film: "120",
    lens: "",
    focal: "",
    shutter: "",
    condition: "",
    acquired: "",
    value: "",
    notes: "A pseudo-TLR box camera with an oversized waist-level viewfinder, hence \"Ful-Vue.\" Clearly badged on the front; this is the camera that was originally (and incorrectly) considered as a photo match for the Ensign Carbine No. 1 above before being identified as its own separate unit.",
    history: "",
    photos: ["https://murraydeathdesigns.github.io/assets/images/cameras/ensign-ful-vue-1.jpg"],
  },
  {
    name: "Praktica FX3",
    company: "KW (Kamera-Werkstätten) / VEB Pentacon",
    year: "",
    country: "East Germany",
    film: "35mm",
    lens: "",
    focal: "",
    shutter: "Focal-plane (cloth)",
    condition: "",
    acquired: "",
    value: "",
    notes: "A screw-mount 35mm SLR from the Praktica line out of Dresden, clearly badged \"Praktica FX3\" on the prism housing.",
    history: "",
    photos: ["https://murraydeathdesigns.github.io/assets/images/cameras/praktica-fx3-1.jpg"],
  },
  {
    name: "Kodak Ektar H35",
    company: "Kodak (Reto Project)",
    year: "",
    country: "USA",
    film: "35mm (Half Frame)",
    lens: "",
    focal: "",
    shutter: "",
    condition: "Excellent",
    acquired: "",
    value: "",
    notes: "A modern half-frame point-and-shoot sold under the Kodak Ektar name, good for doubling a roll's exposure count.",
    history: "",
    photos: ["https://murraydeathdesigns.github.io/assets/images/cameras/kodak-ektar-h35-1.jpg"],
  },
  {
    name: "Spartus",
    company: "Spartus Corporation",
    year: "",
    country: "USA",
    film: "",
    lens: "",
    focal: "",
    shutter: "",
    condition: "",
    acquired: "",
    value: "",
    notes: "A simple black bakelite box camera, badged \"Spartus, Made in U.S.A.\" on the front plate.",
    history: "",
    photos: ["https://murraydeathdesigns.github.io/assets/images/cameras/spartus-1.jpg"],
  },
  {
    name: "Holga 120N",
    company: "Universal Electric (Holga)",
    year: "",
    country: "China",
    film: "120 (Medium Format)",
    lens: "Plastic meniscus",
    focal: "",
    shutter: "",
    condition: "",
    acquired: "",
    value: "",
    notes: "The classic cult toy camera, prized for its light leaks, vignetting, and soft plastic-lens rendering.",
    history: "",
    photos: ["https://murraydeathdesigns.github.io/assets/images/cameras/holga-120n-1.jpg"],
  },
  {
    name: "Foldex 20",
    company: "Pho-Tak Corp.",
    year: "",
    country: "USA",
    film: "620",
    lens: "88mm Octavar",
    focal: "88mm",
    shutter: "Synchromatic, Time/1/50",
    condition: "",
    acquired: "",
    value: "",
    notes: "A mid-century Chicago-made folding camera, badged \"Foldex 20\" with an 88mm Octavar lens and Pho-Tak Synchromatic shutter.",
    history: "",
    photos: ["https://murraydeathdesigns.github.io/assets/images/cameras/foldex-20-1.jpg"],
  },
  {
    name: "Anscomatic SC/8",
    company: "Ansco (GAF)",
    year: "",
    country: "USA",
    film: "Super 8",
    lens: "15mm f/1.8",
    focal: "15mm",
    shutter: "",
    condition: "",
    acquired: "",
    value: "",
    notes: "A Super 8 movie camera, not a still camera like the rest of the archive, but it was in the same folder and clearly badged \"Anscomatic.\"",
    history: "",
    photos: ["https://murraydeathdesigns.github.io/assets/images/cameras/anscomatic-sc8-1.jpg"],
  },
  {
    name: "Chuzhao TLR",
    company: "Chuzhao",
    year: "",
    country: "China",
    film: "35mm",
    lens: "",
    focal: "",
    shutter: "",
    condition: "New",
    acquired: "",
    value: "",
    notes: "A modern novelty camera styled after a classic twin-lens reflex, badged \"Chuzhao\" with \"Capture the essence of every moment\" printed above the taking lens.",
    history: "",
    photos: ["https://murraydeathdesigns.github.io/assets/images/cameras/chuzhao-1.jpg"],
  },
  {
    name: "Zorkiy-4",
    company: "KMZ (Krasnogorsk Mechanical Plant)",
    year: "",
    country: "Soviet Union",
    film: "35mm",
    lens: "",
    focal: "",
    shutter: "",
    condition: "Good",
    acquired: "",
    value: "",
    notes: "A Leica-inspired Soviet rangefinder, badged \"Зоркий-4\" (Cyrillic for \"Zorkiy-4\") on the top plate.",
    history: "",
    photos: [
      "https://murraydeathdesigns.github.io/assets/images/cameras/zorkiy-4-1.jpg",
      "https://murraydeathdesigns.github.io/assets/images/cameras/zorkiy-4-2.jpg",
    ],
  },
];
